# -*- coding: utf-8 -*-
"""APP.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1di96AGvi6Pn1eJDyXvxONeGDEaFSJbwT
"""

pip install streamlit yfinance pandas numpy matplotlib seaborn

pip install plotly

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import yfinance as yf
# import pandas as pd
# import numpy as np
# import matplotlib.pyplot as plt
# 
# # Configuración inicial de la app
# st.set_page_config(page_title="Simulación Financiera", layout="wide")
# st.title("📈 Simulación de Escenarios de Inversión")
# 
# # --- Entrada de datos ---
# tickers = st.text_input("Ingrese los tickers separados por coma (ej: AAPL, MSFT, NVDA):", "AAPL, MSFT")
# tickers = [t.strip().upper() for t in tickers.split(",")]
# 
# start_date = st.date_input("Fecha de inicio", value=pd.to_datetime("2020-01-01"))
# end_date = st.date_input("Fecha de fin", value=pd.to_datetime("today"))
# num_simulations = st.slider("Número de simulaciones Monte Carlo:", 100, 5000, 1000)
# 
# # --- Descargar datos ---
# if st.button("Ejecutar simulación"):
#     data = yf.download(tickers, start=start_date, end=end_date)["Adj Close"]
# 
#     st.subheader("Datos históricos")
#     st.line_chart(data)
# 
#     # --- Cálculos de retornos ---
#     daily_returns = data.pct_change().dropna()
#     mean_returns = daily_returns.mean()
#     cov_matrix = daily_returns.cov()
# 
#     st.write("**Retornos promedio diarios:**")
#     st.dataframe(mean_returns)
# 
#     # --- Simulación Monte Carlo ---
#     num_days = 252  # 1 año de trading
#     portfolio_results = []
# 
#     st.subheader("Simulación Monte Carlo")
# 
#     for i in range(num_simulations):
#         weights = np.random.random(len(tickers))
#         weights /= np.sum(weights)
# 
#         # Simular rendimiento del portafolio
#         sim_returns = np.random.multivariate_normal(mean_returns, cov_matrix, num_days)
#         daily_portfolio_returns = np.dot(sim_returns, weights)
#         cumulative_return = np.cumprod(1 + daily_portfolio_returns)
# 
#         portfolio_results.append(cumulative_return[-1])
# 
#     # --- Mostrar resultados ---
#     fig, ax = plt.subplots()
#     ax.hist(portfolio_results, bins=50, alpha=0.7)
#     ax.set_title("Distribución de rendimientos simulados")
#     ax.set_xlabel("Rendimiento final (1 año)")
#     ax.set_ylabel("Frecuencia")
#     st.pyplot(fig)
# 
#     st.success(f"Simulación completada con {num_simulations} escenarios.")
# 
#     st.write(f"Rendimiento promedio simulado: {np.mean(portfolio_results):.2f}")
#     st.write(f"Rendimiento máximo simulado: {np.max(portfolio_results):.2f}")
#     st.write(f"Rendimiento mínimo simulado: {np.min(portfolio_results):.2f}")
#