# -*- coding: utf-8 -*-
"""MI PRIMER APP.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19coFD_2iQM7imP_g4OMIuV_cQhU1zYW_
"""

#!pip install streamlit

# importamos librerias
import streamlit as st
import pandas as pd
import yfinance as yf

st.title ("Mi Primer APP en Streamlit🕹️")

# lista de tickers inicial

lista_tickers = ["AAPL", "MSFT", "NVDA", "META"]

# multiselector

ticker = st.multiselect("Selecciona un ticker o varios", lista_tickers)

# Boton

if st.button("Descargar"):
    data = yf.download(ticker, period= "1mo")["close"]
    st.subheader("📠 precios de cierre")
    st.dataframe(data)
